-- AlterEnum: novas permissões (Financeiro)
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'CREATE_FINANCE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'UPDATE_FINANCE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'DELETE_FINANCE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'READ_FINANCE';
