-- AlterEnum: novas permissões (Cotações + Auditoria)
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'CREATE_MARKET_QUOTE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'UPDATE_MARKET_QUOTE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'DELETE_MARKET_QUOTE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'READ_MARKET_QUOTE';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'READ_AUDIT';
